server:
  servlet:
    context-path: /pet
  port: 8081


mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ttm.pet.model.dto
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # 逻辑删除配置
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as）
      map-underscore-to-camel-case: true
      cache-enabled: false


spring:
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8

  servlet:
      multipart:
        max-file-size: 10Mb
        max-request-size: 100Mb

#  redis:
#      # Redis数据库索引（默认为0）
#      database: 0
#      host:
#      port: 6379
#      password:
#      lettuce:
#        pool:
#          # 连接池最大连接数（使用负值表示没有限制）
#          max-active: 30
#          # 连接池中的最大空闲连接
#          max-idle: 30
#          # 连接池中的最小空闲连接
#          min-idle: 0
#          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          max-wait: 30ms
##     连接超时时间（毫秒）默认是2000ms
#      timeout: 2000ms
